//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerApp1 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        //private Gadgeteer.Modules.GHIElectronics.Ethernet_ENC28 ethernet_ENC28;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientSP usbClientSP;
        
        private Gadgeteer.Modules.GHIElectronics.LED7R led7r;
        
        private Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.led7r = new GTM.GHIElectronics.LED7R(2);
            //this.ethernet_ENC28 = new GTM.GHIElectronics.Ethernet_ENC28(6);
            this.temperatureHumidity = new GTM.Seeed.TemperatureHumidity(3);
            this.usbClientSP = new GTM.GHIElectronics.UsbClientSP(8);
        }
    }
}
